import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Maulana Syafikh Alkhudri | My Portfolio",
  description: "Fullstack Developer.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Maulana Syafikh Alkhudri",
    url: "https://github.com/SyafikhAL010907",
  },
  icons: {
    icon: "/logo-unj.png?v=99",
    apple: "/logo-unj.png?v=99",
  },
} as const;
